### ISSUE TITLE
日志记录器记录到错误

### ISSUE THREAD

**Issue by liyufan** [GhostFlying/LocationReportEnabler#70]
FATAL EXCEPTION: main
 Process: org.cafeboy.locationreportenabler, PID: 2456
 java.lang.RuntimeException: Unable to start receiver com.ghostflying.locationreportenabler.EnablerReceiver: java.lang.StringIndexOutOfBoundsException: length=100; regionStart=0; regionLength=-1
 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3181)
 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:154)
 	at android.app.ActivityThread.main(ActivityThread.java:6322)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
 Caused by: java.lang.StringIndexOutOfBoundsException: length=100; regionStart=0; regionLength=-1
 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:69)
 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:53)
 	at com.ghostflying.locationreportenabler.PropUtil.getShellOutput(PropUtil.java:152)
 	at com.ghostflying.locationreportenabler.PropUtil.setFakerCarrierForDualCard(PropUtil.java:114)
 	at com.ghostflying.locationreportenabler.PropUtil.setFakeCarrier(PropUtil.java:100)
 	at com.ghostflying.locationreportenabler.PropUtil.enableLocationReport(PropUtil.java:46)
 	at com.ghostflying.locationreportenabler.EnablerReceiver.onReceive(EnablerReceiver.java:24)
 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3169)
 	... 8 more

**Comment by GhostFlying** [comment]
我记得没错的话这是一个已经修复的 bug，请告诉我你的版本号

**Comment by liyufan** [comment]
@GhostFlying Play上的最新版1.4.3general

**Comment by GhostFlying** [comment]
更新到 release 页面的 1.4.5 应该就修复了
